<?php
check( ! cleanup_indexable_post( $article ), 'published alone does not permit indexing' );
check( ! is_wp_error( cleanup_set_indexable( $article, true ) ), 'reviewer enables indexing' );
check( cleanup_indexable_post( $article ), 'content hash matches index approval' );
wp_set_current_user( $editor );
check( is_wp_error( cleanup_set_indexable( $article, true ) ), 'editor cannot enable indexing' );
check( is_wp_error( cleanup_review_archive( '/scam/', 'title', 'intro' ) ), 'editor cannot approve archive' );
wp_set_current_user( 1 );
check( false === cleanup_archive_args( '/company/wrong-pref/' ), 'unknown region cannot be approved' );
check( is_wp_error( cleanup_review_archive( '/price/', '料金', '独自の解説' ) ), 'empty archive cannot be indexed' );
check( ! is_wp_error( cleanup_review_archive( '/scam/', '手口と確認事項', 'このカテゴリー固有の検証用解説です。' ) ), 'nonempty reviewed archive accepted' );
check( cleanup_indexable_archive( '/scam/' ), 'archive hash accepted' );
$provider = new Cleanup_Sitemap_Provider(); $urls = array_column( $provider->get_url_list( 1 ), 'loc' );
check( in_array( get_permalink( $article ), $urls, true ), 'sitemap includes approved index target' );
check( ! in_array( get_permalink( $company ), $urls, true ), 'sitemap excludes unapproved company' );
check( in_array( home_url( '/scam/' ), $urls, true ), 'sitemap includes reviewed archive' );
check( array() === $provider->get_url_list( 2 ), 'sitemap pagination has no duplicates' );
wp_update_post( array( 'ID' => $article, 'post_content' => '変更後の確認用記事' ) );
check( ! cleanup_indexable_post( $article ), 'edited content excluded from indexing' );
check( ! cleanup_indexable_archive( '/scam/' ), 'changed archive membership requires re-review' );
cleanup_approve( $article, cleanup_fingerprint( $article ) );
check( ! cleanup_indexable_post( $article ), 'publication reapproval alone does not restore stale SEO approval' );
cleanup_set_indexable( $article, true );
$old_url = get_permalink( $article );
wp_set_object_terms( $article, 'industry', 'article_type' );
check( '' === cleanup_redirect_target( wp_parse_url( $old_url, PHP_URL_PATH ) ), 'no redirect to draft' );
cleanup_approve( $article, cleanup_fingerprint( $article ) );
check( cleanup_redirect_target( wp_parse_url( $old_url, PHP_URL_PATH ) ) === get_permalink( $article ), 'old category path redirects to approved current URL' );
wp_set_object_terms( $article, 'scam', 'article_type' ); cleanup_approve( $article, cleanup_fingerprint( $article ) ); cleanup_set_indexable( $article, true );
check( '' === cleanup_redirect_target( '/scam/test-scam/' ), 'redirect cannot point to itself' );
wp_update_post( array( 'ID' => $article, 'post_name' => 'test-scam-renamed' ) ); cleanup_approve( $article, cleanup_fingerprint( $article ) ); cleanup_set_indexable( $article, true );
cleanup_review_archive( '/scam/', '手口と確認事項', 'このカテゴリー固有の検証用解説です。' );
cleanup_set_indexable( $municipality, true );
check( ! is_wp_error( cleanup_review_archive( '/municipality/test-pref/', '検証県の処分方法', '検証県に固有の説明です。' ) ), 'regional archive review succeeds' );
check( ! cleanup_indexable_archive( '/company/test-pref/' ), 'unreviewed regional archive excluded' );
$second = fixture( 'article', 'test-scam-second' ); wp_set_object_terms( $second, 'scam', 'article_type' ); cleanup_approve( $second, cleanup_fingerprint( $second ) ); cleanup_set_indexable( $second, true );
check( ! cleanup_indexable_archive( '/scam/' ), 'new index target invalidates archive review' );
cleanup_review_archive( '/scam/', '手口と確認事項', 'このカテゴリー固有の検証用解説です。' );
$related_ids = wp_list_pluck( cleanup_related_posts( $article ), 'ID' );
check( in_array( $second, $related_ids, true ) && ! in_array( $article, $related_ids, true ), 'related articles share context and exclude self' );
update_option( 'posts_per_page', 1 );
// Only the isolated test instance is made crawlable, for HTTP robots/sitemap checks.
update_option( 'blog_public', 1 );
