import assert from 'node:assert/strict';
import {readFile,mkdir,writeFile,readdir} from 'node:fs/promises';
import path from 'node:path';
import {boot} from './runtime.mjs';
const results=[];
const server=await boot({port:9401,storage:'test-'+Date.now()});
const base=server.serverUrl;
async function check(name,fn){try{await fn();results.push({name,status:'passed'});console.log('PASS',name);}catch(e){results.push({name,status:'failed',error:e.message});console.error('FAIL',name,e.message);}}
async function php(code){const result=await server.playground.run({code:'<?php require_once "/wordpress/wp-load.php"; '+code});if(result.exitCode!==0)throw Error(result.errors||result.text);return result.text;}
try{
 await check('全PHPファイルの構文検査',async()=>{const list=[];async function walk(dir){for(const e of await readdir(dir,{withFileTypes:true})){const p=path.join(dir,e.name);if(e.isDirectory())await walk(p);else if(p.endsWith('.php'))list.push(p);}}await walk('wordpress');for(const file of list){const code=await readFile(file,'utf8');const result=await server.playground.run({code:'<?php token_get_all(base64_decode("'+Buffer.from(code).toString('base64')+'"), TOKEN_PARSE); echo "OK";'});assert.equal(result.text,'OK',file);}});
 await check('主要ページと未知URLのHTTPステータス',async()=>{for(const route of ['/','/company/','/area/','/area/tokyo/setagaya/','/area/kanagawa/kawasaki/','/disposal/sofa/','/read/estimate-checklist/','/about/','/privacy/','/staff/','/case/']){const r=await fetch(base+route);assert.equal(r.status,200,route);const html=await r.text();assert(!html.includes('Fatal error'),route);assert(html.includes('かたづけの手帖'),route);}assert.equal((await fetch(base+'/missing-route-abc/')).status,404);});
 await check('試験サイトのnoindex・canonical・Schema',async()=>{const html=await(await fetch(base+'/read/estimate-checklist/')).text();assert.match(html,/noindex/);assert.equal((html.match(/rel=['"]canonical['"]/g)||[]).length,1);assert.match(html,/application\/ld\+json/);assert.match(html,/city.setagaya.lg.jp/);});
 await check('非認証管理APIを拒否',async()=>{const r=await fetch(base+'/wp-json/portal/v1/dashboard');assert([401,403].includes(r.status));});
 const sr=await fetch(base+'/wp-json/portal/v1/session');const cookie=sr.headers.get('set-cookie').split(';')[0];const token=(await sr.json()).token;
 async function api(route,data,extra={}){return fetch(base+'/wp-json/portal/v1/'+route,{method:'POST',headers:{'content-type':'application/json',origin:base,cookie,'x-portal-token':token,...extra},body:JSON.stringify(data)});}
 const conditions={area:'tokyo/setagaya',items:['sofa'],night:false,same_day:false};
 await check('トークン・Originの不正を拒否',async()=>{assert.equal((await api('matches',conditions,{'x-portal-token':'bad'})).status,403);assert.equal((await api('matches',conditions,{origin:'https://evil.example'})).status,403);});
 let partners;
 await check('一致候補・夜間条件・不正品目',async()=>{const r=await api('matches',conditions);assert.equal(r.status,200);partners=(await r.json()).partners;assert.equal(partners.length,2);assert(!('fee_rate' in partners[0]));const night=await(await api('matches',{...conditions,night:true})).json();assert.equal(night.partners.length,1);assert.equal((await api('matches',{...conditions,items:['invalid']})).status,400);});
 let leadId;const request={...conditions,name:'試験 太郎',email:'test@example.com',partner_id:partners?.[0]?.id,consent:true,idempotency_key:crypto.randomUUID()};
 await check('実メール・未同意の問い合わせを拒否',async()=>{assert.equal((await api('leads',{...request,email:'someone@gmail.com'})).status,400);assert.equal((await api('leads',{...request,consent:false})).status,400);});
 await check('問い合わせ保存・Lead ID・二重送信防止',async()=>{const r=await api('leads',request);const body=await r.json();assert.equal(r.status,201,JSON.stringify(body));leadId=body.lead_id;assert.match(leadId,/^LEAD-\d{8}-\d{6,}$/);const duplicate=await api('leads',request);assert.equal((await duplicate.json()).lead_id,leadId);assert.equal((await api('leads',{...request,name:'変更'})).status,409);});
 await check('連絡先の暗号化・件数・契約スナップショット',async()=>{const data=JSON.parse(await php('global $wpdb; $l=$wpdb->get_row("SELECT * FROM ".portal_table("leads")." LIMIT 1",ARRAY_A);$c=$wpdb->get_var("SELECT encrypted_payload FROM ".portal_table("contacts")." LIMIT 1");echo wp_json_encode(["count"=>(int)$wpdb->get_var("SELECT COUNT(*) FROM ".portal_table("leads")),"encrypted"=>$c,"contact"=>portal_decrypt($c),"fee"=>$l["fee_rate"]]);'));assert.equal(data.count,1);assert(!data.encrypted.includes('test@example.com'));assert.equal(data.contact.email,'test@example.com');assert.equal(Number(data.fee),3000);});
 await check('成約・紹介料計上・重複更新拒否・取消仕訳',async()=>{const data=JSON.parse(await php('wp_set_current_user(1);global $wpdb;$id=(int)$wpdb->get_var("SELECT id FROM ".portal_table("leads")." LIMIT 1");$a=portal_change_status($id,1,"sent",0);$b=portal_change_status($id,2,"converted",30000);$revenue=portal_dashboard_data()["revenue"];$duplicate=portal_change_status($id,2,"converted",30000);$cancel=portal_change_status($id,3,"cancelled",0);echo wp_json_encode(["a"=>$a,"b"=>$b,"revenue"=>$revenue,"duplicate"=>is_wp_error($duplicate),"cancel"=>$cancel,"net"=>portal_dashboard_data()["revenue"]]);'));assert.equal(data.a,true);assert.equal(data.b,true);assert.equal(data.revenue,3000);assert.equal(data.duplicate,true);assert.equal(data.cancel,true);assert.equal(data.net,0);});
 await check('紹介料・自社属性で候補順が変わらない',async()=>{const data=JSON.parse(await php('$r=["area"=>"tokyo/setagaya","items"=>["sofa"],"night"=>false,"same_day"=>false];$before=array_column(portal_partners($r),"id");global $wpdb;$wpdb->query("UPDATE ".portal_table("partners")." SET fee_rate=99999,partner_type=\"internal\" WHERE id=2");$after=array_column(portal_partners($r),"id");echo wp_json_encode([$before,$after]);'));assert.deepEqual(data[0],data[1]);});
 await check('受付上限の最終確認・枠不足時に保存しない',async()=>{await php('global $wpdb;$wpdb->query("UPDATE ".portal_table("partners")." SET monthly_limit=current_leads WHERE id=1");');assert.equal((await api('leads',{...request,idempotency_key:crypto.randomUUID()})).status,409);});
 await check('公開ゲートは非承認記事を下書きへ戻す',async()=>{const result=await php('wp_set_current_user(1);$id=wp_insert_post(["post_type"=>"article","post_title"=>"未確認テスト","post_status"=>"publish"]);echo get_post_status($id);');assert.equal(result,'draft');});
 await check('紹介料計算の端数・未知方式',async()=>{const data=JSON.parse(await php('echo wp_json_encode([portal_fee("conversion_percent",1234,12345),portal_fee("lead",500,999),portal_fee("unknown",999,10000)]);'));assert.deepEqual(data,[1523,500,0]);});
}finally{await mkdir('artifacts',{recursive:true});await writeFile('artifacts/test-results.json',JSON.stringify({date:new Date().toISOString(),results},null,2));await server[Symbol.asyncDispose]();}
console.log(`${results.filter(r=>r.status==='passed').length}/${results.length} passed`);if(results.some(r=>r.status==='failed'))process.exitCode=1;
